export const fleet = [
  {
    id: "ferrari-f8",
    name: "Ferrari F8 Tributo",
    brand: "Ferrari",
    category: "Supercar",
    tag: "VIP Flagship",
    image: "https://images.unsplash.com/photo-1592198084033-aade902d1aae?auto=format&fit=crop&w=1200&q=80",
    power: "710 HP",
    acceleration: "2.9s (0-100)",
    topSpeed: "340 km/h",
    engine: "3.9L Twin-Turbo V8",
    transmission: "7-Speed Dual-Clutch F1",
    fuel: "Petrol",
    seats: "2 Seats",
    dailyRate: 45000,
    hourlyRate: 6500,
    description: "The ultimate Italian thoroughbred. Explosive acceleration with iconic aerodynamic styling for red-carpet VIP moments."
  },
  {
    id: "lambo-huracan",
    name: "Lamborghini Huracán EVO",
    brand: "Lamborghini",
    category: "Supercar",
    tag: "Celebrity Choice",
    image: "https://images.unsplash.com/photo-1544829099-b9a0c07fad1a?auto=format&fit=crop&w=1200&q=80",
    power: "631 HP",
    acceleration: "3.1s (0-100)",
    topSpeed: "325 km/h",
    engine: "5.2L Naturally Aspirated V10",
    transmission: "7-Speed LDF Dual Clutch",
    fuel: "Petrol",
    seats: "2 Seats",
    dailyRate: 48000,
    hourlyRate: 7000,
    description: "Naturally aspirated roaring V10 power that commands attention everywhere you arrive in Pandharpur."
  },
  {
    id: "ford-mustang-gt",
    name: "Ford Mustang GT 5.0 V8",
    brand: "Ford",
    category: "Muscle",
    tag: "Wedding Special",
    image: "https://images.unsplash.com/photo-1584345604476-8ec5e12e42dd?auto=format&fit=crop&w=1200&q=80",
    power: "450 HP",
    acceleration: "4.3s (0-100)",
    topSpeed: "250 km/h",
    engine: "5.0L Coyote V8",
    transmission: "10-Speed SelectShift Automatic",
    fuel: "Petrol",
    seats: "4 Seats (2+2)",
    dailyRate: 22000,
    hourlyRate: 3500,
    description: "American muscle heritage with a throaty exhaust roar. Perfect for grand wedding entries and cinematic reels."
  },
  {
    id: "porsche-911",
    name: "Porsche 911 Carrera S",
    brand: "Porsche",
    category: "Supercar",
    tag: "Best Seller",
    image: "https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?auto=format&fit=crop&w=1200&q=80",
    power: "443 HP",
    acceleration: "3.5s (0-100)",
    topSpeed: "308 km/h",
    engine: "3.0L Twin-Turbo Flat-6",
    transmission: "8-Speed Porsche PDK",
    fuel: "Petrol",
    seats: "2+2 Seats",
    dailyRate: 35000,
    hourlyRate: 5000,
    description: "German engineering perfection. Supreme precision, timeless silhouette, and unmatched grand touring luxury."
  },
  {
    id: "bmw-z4-roadster",
    name: "BMW Z4 M40i Convertible",
    brand: "BMW",
    category: "Convertible",
    tag: "Open-Top Glamour",
    image: "https://images.unsplash.com/photo-1555353540-64580b51c258?auto=format&fit=crop&w=1200&q=80",
    power: "382 HP",
    acceleration: "4.1s (0-100)",
    topSpeed: "250 km/h",
    engine: "3.0L TwinPower Turbo Inline-6",
    transmission: "8-Speed Sport Steptronic",
    fuel: "Petrol",
    seats: "2 Seats",
    dailyRate: 26000,
    hourlyRate: 4000,
    description: "Drop the top and feel the breeze. The quintessential open-air supercar for romantic pre-wedding shoots."
  },
  {
    id: "mercedes-amg-g63",
    name: "Mercedes-AMG G63 BiTurbo",
    brand: "Mercedes-Benz",
    category: "Luxury SUV",
    tag: "VIP Royal Escort",
    image: "https://images.unsplash.com/photo-1520050206274-a1ae44613e6d?auto=format&fit=crop&w=1200&q=80",
    power: "577 HP",
    acceleration: "4.5s (0-100)",
    topSpeed: "240 km/h",
    engine: "4.0L V8 Biturbo Handcrafted",
    transmission: "9-Speed AMG SPEEDSHIFT",
    fuel: "Petrol",
    seats: "5 Seats",
    dailyRate: 55000,
    hourlyRate: 8000,
    description: "The King of the road. Unmatched VIP road presence, side-exit exhaust note, and armored-grade luxury."
  }
];

export default fleet;
